import asideEventsDisplayListener from "./events/asideEventsDisplayListener.js";
import calendarEventInfoCloseListener from "./events/calendarEventInfoCloseListener.js";
import calendarEventInfoDisplayListener from "./events/calendarEventInfoDisplayListener.js";
import calendarEventFormCloseListener from "./events/calendarEventFormCloseListener.js";
import calendarEventFormDisplayListener from "./events/calendarEventFormDisplayListener.js";
import calendarEventFormChangeListener from "./events/calendarEventFormChangeListener.js";
import calendarEventFormSubmitListener from "./events/calendarEventFormSubmitListener.js";
import calendarEventRemoveListener from "./events/calendarEventRemoveListener.js";
import updateCalendarListener from "./events/updateCalendarListener.js";
import changeFormStylesListener from "./events/changeFormStylesListener.js";
import filterEventTagsByTypeListener from "./events/filterEventTagsByTypeListener.js";
import init from "./events/init.js";

asideEventsDisplayListener();
calendarEventFormDisplayListener();
calendarEventFormCloseListener();
calendarEventFormChangeListener();
calendarEventFormSubmitListener();
calendarEventInfoCloseListener();
calendarEventInfoDisplayListener();
calendarEventRemoveListener();
updateCalendarListener();
changeFormStylesListener();
filterEventTagsByTypeListener();
init();
