import changeFormStylesListener from "./events/changeFormStylesListener.js";
import closeDayInfoListener from "./events/closeDayInfoListener.js";
import closeEventFormListener from "./events/closeEventFormListener.js";
import closeEventInfoListener from "./events/closeEventInfoListener.js";
import displayDayInfoListener from "./events/displayDayInfoListener.js";
import displayEventFormListener from "./events/displayEventFormListener.js";
import displayEventInfoListener from "./events/displayEventInfoListener.js";
import filterEventsByTypeListener from "./events/filterEventsByTypeListener.js";
import init from "./events/init.js";
import inputEventFormListener from "./events/inputEventFormListener.js";
import removeCalendarEventListener from "./events/removeCalendarEventListener.js";
import saveCalendarEventListener from "./events/saveCalendarEventListener.js";
import updateCalendarListener from "./events/updateCalendarListener.js";

changeFormStylesListener();
closeDayInfoListener();
closeEventFormListener();
closeEventInfoListener();
displayDayInfoListener();
displayEventFormListener();
displayEventInfoListener();
filterEventsByTypeListener();
init();
inputEventFormListener();
removeCalendarEventListener();
saveCalendarEventListener();
updateCalendarListener();
